project:
  type: website

website:
  title: "PharmaTechHub"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blogs
        text: Blogs
      - about.qmd
  favicon: images/logo.jpg
  site-url: https://pharmatechhub.com
  body-footer: | 
     
  margin-footer: |
    
  

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

